version: 4.29.0
markdownExploder: true
paths:
  outputBase: docs
  featurePrefix: feature-claude-transcript-loading
prd:
  prdFile: '{{paths.outputBase}}/{{paths.featurePrefix}}/prd.md'
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: '{{paths.outputBase}}/{{paths.featurePrefix}}/prd'
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: '{{paths.outputBase}}/{{paths.featurePrefix}}/architecture.md'
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: '{{paths.outputBase}}/{{paths.featurePrefix}}/architecture'
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - '{{paths.outputBase}}/{{paths.featurePrefix}}/architecture/coding-standards.md'
  - '{{paths.outputBase}}/{{paths.featurePrefix}}/architecture/tech-stack.md'
  - '{{paths.outputBase}}/{{paths.featurePrefix}}/architecture/source-tree.md'
devDebugLog: .ai/debug-log.md
devStoryLocation: '{{paths.outputBase}}/{{paths.featurePrefix}}/stories'
slashPrefix: BMad
